### ISSUE TITLE
Look into a 'sidebar' layout for certain pages

### ISSUE THREAD

**Issue by cal-overflow** [cal-overflow/Build-A-Blog#53]

**Comment by ChristianLisle** [comment]
Closing this as I've decided I don't want a sidebar.

**Comment by cal-overflow** [comment]
Reopening this as I've changed my mind

**Comment by cal-overflow** [comment]
Closing this as it can be implemented as a new "View." I wouldn't use this feature myself, so I'm not going to bother. Someone else is free to implement this, but it's nowhere near a priority for the template.
